### ISSUE TITLE
over read error

### ISSUE THREAD

**Issue by alexk195** [jacobfeder/axisfifo#5]
If transmitting larger packets over fifo in non-blocking mode it comes to over-read error after certain data amount is transmitted.
The proposed solution is to check occupancy and rxLength so that all bytes indicated by rxLength are in the fifo.

**Comment by jacobfeder** [comment]
Can you explain error conditions in more detail and attach output?

**Comment by alexk195** [comment]
I have two fifos connected with each other using Axi-Stream Interface. The length register of Fifo which is handled by kernel module is named S-Fifo. The other fifo is R-Fifo. I write frames to R-Fifo and read them from S-Fifo. Small frames are working fine. On bigger frames if written fast one after each other I had over-read errors.  As far as I've tracked this the "read length register" can indicate data which is about to be written to Fifo but it must not be actually written completely. The "occupancy" register is actually the one which indicates how many data is written.  Unfortunatelly the length register is not allowed to be polled many times. Only occupancy register is allowed to be polled. So I suppose the solution would be to wait until occupancy is >0. Read the length register once. Wait until occupancy indicates that all data is in fifo. Then perform complete read.

**Comment by alexk195** [comment]
Oops I closed issue by accident...

**Comment by jacobfeder** [comment]
Sorry it's been awhile since I've worked on this - I need some more data. Can you send your code? Also a picture of your vivado block diagram. Everything required to repeat the error you are getting.

Thanks

**Comment by alexk195** [comment]
Unfortunatelly I cannot share the code or block design for certain reasons. There are two Fifos R and S. 
Both connected cross-over on Axi-S site. The R-Fifo is controlled by Bare-Metal app using Xilinx BSP. The S-Fifo is controlled using Your kernel module. The direction S->R works, the direction R->S works only with short data packages. 
The configuration of Fifos is as follows:
Data Interface : Axi4 Lite,
Enabled checkboxes: Enable Transmit Data, Enable Receive Data, TKEEP
Receive/Transmit Fifo Depth: 512
Full Threshold 507
Empty Threshold 2

**Comment by alexk195** [comment]
I will try to fix it next week and create pull request.

**Comment by jacobfeder** [comment]
How large are the packets you're trying to send? If they're bigger than 512 you might have an issue... (notice the transmit FIFO depth)

"Only occupancy register is allowed to be polled. So I suppose the solution would be to wait until occupancy is >0. Read the length register once. Wait until occupancy indicates that all data is in fifo. Then perform complete read."

Yeah so currently it does something similar to that - it waits until occupancy > 0 (RDFO), it reads the RLR to get the number of bytes, then it reads the bytes out. However it does NOT "Wait until occupancy indicates that all data is in fifo". This shouldn't be necessary because the RDFO only gets updated after a full packet is received.

Good luck, let me know if there's something I can do to help. Take a very close look at the description of the IP registers in the datasheet:
https://www.xilinx.com/support/documentation/ip_documentation/axi_fifo_mm_s/v4_1/pg080-axi-fifo-mm-s.pdf
